title: Daniel Shen
description: [Description]
author: Daniel Shen
email: daniel.shen0987@gmail.com
phone: (647) 831-7889
github: https://github.com/UncreativeName1
about: [About Me]
disqus_shortname: programming
# google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-asterisk
      link: "https://dmoj.ca/user/UncreativeName"
    - icon: fa-github
      link: "https://github.com/UncreativeName1"

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://uncreativename1.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
